### ISSUE TITLE
Rename post to tweet

### ISSUE THREAD

**Issue by twitter7** [JosePascual/restore-birdie#2]
Hello!

Can you please rename Post to tweet?

thanks!

i appreciate what you are doing.

**Comment by JosePascual** [comment]
I have renamed a couple of buttons.

The changes are being reviewed and as soon as they are approved, you will be able to see them on Twitter

**Comment by JosePascual** [comment]
✅  [1.2 Published](https://chrome.google.com/webstore/detail/restore-birdie/kidijlmplbolmcnldaaphjebgnadoeod)
