### ISSUE TITLE
Icon no longer is updated

### ISSUE THREAD

**Issue by NotMerky** [JosePascual/restore-birdie#3]
As the title suggests, the X logo is back, unfortunately.

**Comment by JosePascual** [comment]
✅  I have solved the problem.

Twitter is changing small things in the DOM structure and that caused some incorrect selections.

Currently the fix has been submitted for review, as soon as it is accepted the extension should be back to behaving as expected.

**Comment by JosePascual** [comment]
✅  [1.2 Published](https://chrome.google.com/webstore/detail/restore-birdie/kidijlmplbolmcnldaaphjebgnadoeod)
